services:
  db:
    image: postgres:16-alpine
    container_name: qa-postgres
    environment:
      POSTGRES_USER: qa_user
      POSTGRES_PASSWORD: qa_pass
      POSTGRES_DB: qa_db
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U qa_user -d qa_db"]
      interval: 5s
      timeout: 3s
      retries: 5
      start_period: 5s

  cache:
    image: redis:7-alpine
    container_name: qa-redis

  adminer:
    image: adminer:latest
    container_name: qa-adminer
    ports:
      - "8888:8080"
    depends_on:
      db:
        condition: service_healthy

volumes:
  db-data: